spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/...
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
